import 'package:flutter/material.dart';

class ReactionPicker extends StatelessWidget {
  final void Function(String) onReactionSelected;

  const ReactionPicker({super.key, required this.onReactionSelected});

  @override
  Widget build(BuildContext context) {
    final reactions = [
      '👍',
      '❤️',
      '😂',
      '😮',
      '😢',
      '👏',
      '🎉',
      '🔥',
      '😡',
      '☠️',
      '😊',
      '😂',
      '🤣',
      '❤️',
      '😘',
      '🙌',
      '🤞',
      '✌️',
      '🤷‍♀️',
      '🤦‍♀️',
      '😎',
      '🤩',
      '🤔',
      '🫡',
      '🤨',
      '😐',
      '😑',
      '😶',
      '🫥',
      '😮',
      '😥',
      '😣',
      '😏',
      '🙄',
      '😶‍🌫️',
      '🤐',
      '😯',
      '😪',
      '😫',
      '🥱',
      '😴',
      '😌',
      '😛',
      '😜',
      '😝',
      '🤤',
      '😒',
      '🫠',
      '🙃',
      '🫤',
      '😕',
      '😔',
      '😓',
      '🤑',
      '😲',
      '☹️',
      '🙁',
      '😖',
      '😞',
      '😟',
      '😤',
      '😢',
      '😭',
      '😦',
      '😧',
      '😰',
      '😮‍💨',
      '😬',
      '🤯',
      '😩',
      '😨',
      '😱',
      '🥵',
      '🥶',
      '😳',
      '🤪',
      '😵',
      '😷',
      '🤬',
      '😡',
      '😠',
      '🥴',
      '😵‍💫',
      '🤒',
      '🤕',
      '🤢',
      '🤮',
      '🤧',
      '😇',
    ];

    return Wrap(
      spacing: 4.0,
      runSpacing: 4.0,
      children: reactions.map((reaction) {
        return Material(
          color: Colors.transparent,
          child: InkWell(
            onTap: () => onReactionSelected(reaction),
            borderRadius: BorderRadius.circular(8.0),
            child: Container(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                reaction,
                style: const TextStyle(fontSize: 16.0),
              ),
            ),
          ),
        );
      }).toList(),
    );
  }
}
